sudo: required

services:
  - docker

env:
  global:
  - secure: "encrypted-dockerhub-username"
  - secure: "encrypted-dockerhub-password"

language: java

jdk:
  - oraclejdk8

script:
- ./mvn package
- ./mvn docker:build -e

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export IMAGE_NAME=springio/users
- docker push $IMAGE_NAME