sudo: required

services:
  - docker

env:
  global:
  - secure: "encrypted-dockerhub-username"
  - secure: "encrypted-dockerhub-password"

language: java

jdk:
  - oraclejdk8

script:
- ./mvn clean install  -B
- ./mvn package 
- ./mvn docker:build -e

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export IMAGE_NAME=springio/users
- docker push $IMAGE_NAME

after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)
  # deploy snapshots to Maven central, but only from master branch
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && mvn --settings sonatype-settings.xml -DskipTests -B deploy"