server:
  contextPath: /app
  port: 8080
spring:
  application:
    name: users
  #autoconfigure:
    #exclude:
      #- org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      #- org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      #- org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  data:
    rest:
      base-path: /api
  profiles.active: development
  jmx:
    enabled: false
cookie-secret: 8e045a51e4b102ea803c06f92841a1fb
cms-domain: 192.168.187.134
cms-port: 8888
#---

  
---
spring:
  profiles: development
  db-one:
    datasource:
      url: jdbc:postgresql://192.168.187.134:5432/cmsdb
      username: postgres
      password: alex77
      driver-class-name:  org.postgresql.Driver
      test-on-borrow: false
      validation-query: SELECT 1  
      hibernate:
        #default_catalog: danos
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        auditable: true
        envers:
          default_catalog: cmsdb
          storeDataAtDelete : true
          #default_schema : danos
        ejb:
          naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        hbm2ddl:
          auto: update
              #create-drop, validate, update
  rabbitmq:
    host: 192.168.187.134
    port: 5672
    username: joel
    password: joel1